version: '3'

services:
      backend-container:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            FLASK_APP: run:app
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            DB_HOST: db
            PORT: "8080"
        ports:
            - "8080:8080"
        depends_on:
          - db
      db:
        image: postgres:16
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        volumes:
          - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: